stages:
  - depoly

depoly-prod:
  stage: depoly
  script:
    - devops dp --lintCheck=false --delOutputDir=false --useYarnInstall=false --buildCommand=ignoreBuild
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^master/'
  tags:
    - prod-node:12.18
