stages:
  - install_deps
  - depoly

cache:
  paths:
    - node_modules/

install_deps:
  stage: install_deps
  script:
    - SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ sudo npm i
  rules:
    - if: '$CI_COMMIT_TAG'
  tags:
    - node:12.14

depoly:
  stage: depoly
  script:
    - devops dp
  rules:
    - if: '$CI_COMMIT_TAG'
  tags:
    - node:12.14
