stages:
  - install_deps
  - depoly

cache:
  paths:
    - node_modules/

install_deps:
  stage: install_deps
  script:
    - npm i

  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^qatest/'
    - if: '$CI_COMMIT_BRANCH =~ /^pre-release/'
    - if: '$CI_COMMIT_TAG'
  tags:
    - node:12.14

depoly:
  stage: depoly
  script:
    - devops dp --lintCheck=false --buildOutputDir=docs/dist --buildCommand=release:site
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^qatest/'
    - if: '$CI_COMMIT_BRANCH =~ /^pre-release/'
    - if: '$CI_COMMIT_TAG'
  tags:
    - node:12.14
